[package]
name = "rocket"
version = "0.1.0"
authors = ["Takayoshi Nobuoka <taka7.y@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tower-web = "*"
serde_json = "*"
serde = "*"
crossbeam-queue = "*"
